name: flutter_gl_web
description: Web platform implementation of flutter_gl, cross-platform call OpenGL API by Dart through dart:ffi. Provides OpenGL with Texture Widget on Flutter.
version: 0.0.4
publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterGlPlugin
        fileName: flutter_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_gl_platform_interface:
    path: ../flutter_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.2.5 <4.0.0"
